import { writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';

import { appConfig } from '../config.js';
import { getDb, type ThreadRow } from '../db/index.js';
import { getActiveAccount } from '../db/accounts.js';

export function buildDailySummary(options?: { date?: Date }): {
  markdown: string;
  path: string;
  threadCount: number;
} {
  const account = getActiveAccount();
  if (!account) throw new Error('No Gmail account connected');

  const day = options?.date ?? new Date();
  const start = new Date(day);
  start.setHours(0, 0, 0, 0);
  const end = new Date(day);
  end.setHours(23, 59, 59, 999);

  const threads = getDb()
    .prepare(
      `SELECT * FROM threads
       WHERE account_id = ?
         AND last_message_at >= ?
         AND last_message_at <= ?
       ORDER BY last_message_at DESC
       LIMIT 200`,
    )
    .all(account.id, start.getTime(), end.getTime()) as ThreadRow[];

  // Fallback: latest N if none “today” (timezone / empty day)
  const list =
    threads.length > 0
      ? threads
      : (getDb()
          .prepare(
            `SELECT * FROM threads WHERE account_id = ? ORDER BY last_message_at DESC LIMIT 40`,
          )
          .all(account.id) as ThreadRow[]);

  const dateLabel = day.toISOString().slice(0, 10);
  const unread = list.filter((t) => t.unread).length;
  const lines: string[] = [
    `# Mail summary — ${dateLabel}`,
    '',
    `Account: **${account.email}**`,
    `Threads: **${list.length}** · Unread: **${unread}**`,
    '',
    '## Inbox highlights',
    '',
  ];

  for (const t of list.slice(0, 50)) {
    const flag = t.unread ? '●' : '○';
    const star = t.starred ? '★' : '';
    const who = t.from_name || t.from_email || 'Unknown';
    const sub = (t.subject || '(no subject)').replace(/\n/g, ' ');
    const snip = (t.snippet || '').replace(/\n/g, ' ').slice(0, 120);
    lines.push(`- ${flag}${star} **${who}** — ${sub}`);
    if (snip) lines.push(`  - ${snip}`);
  }

  lines.push('', '---', '', `_Generated by Docket · ${new Date().toISOString()}_`, '');

  const markdown = lines.join('\n');
  mkdirSync(appConfig.notesDir, { recursive: true });
  const path = join(appConfig.notesDir, `${dateLabel}.md`);
  writeFileSync(path, markdown, 'utf8');

  return { markdown, path, threadCount: list.length };
}
