import { provideHttpClient } from '@angular/common/http';
import { provideHttpClientTesting } from '@angular/common/http/testing';
import { TestBed } from '@angular/core/testing';

import { App } from './app';
import { UiShellService } from './core/ui-shell.service';

function mockShell() {
  return {
    phaseLabel: () => 'Local Mail',
    coreStatus: () => 'online-disconnected' as const,
    accountEmail: () => null,
    accounts: () => [],
    activeAccountId: () => null,
    isActiveAccount: () => false,
    refreshAccounts: async () => undefined,
    isConnected: () => false,
    handleAuthExpired: () => undefined,
    listLoading: () => false,
    detailLoading: () => false,
    syncing: () => false,
    sending: () => false,
    summaryBusy: () => false,
    aiBusy: () => false,
    lastNotify: () => null,
    dismissNotifyToast: () => undefined,
    openNotifyToast: () => undefined,
    pushNotifyToast: () => undefined,
    aiMode: () => 'ollama',
    aiStatus: () => null,
    aiConfig: () => null,
    aiConfigSaving: () => false,
    refreshAiStatus: async () => undefined,
    saveAiConfig: async () => undefined,
    setAiRole: () => undefined,
    statusMessage: () => null,
    clearStatusMessage: () => undefined,
    undoAvailable: () => false,
    undoCount: () => 0,
    labels: () => [],
    customViews: () => [],
    activeLabelId: () => null,
    activeCustomViewId: () => null,
    emptyInboxHint: () => 'Connect Gmail to load your inbox.',
    threads: () => [],
    selectedId: () => null,
    selectedThread: () => null,
    checkedCount: () => 0,
    checkedIds: () => new Set(),
    isChecked: () => false,
    clearChecked: () => undefined,
    selectAllVisible: () => undefined,
    onThreadListClick: async () => undefined,
    setCheckedRange: () => undefined,
    replyOpen: () => false,
    composeOpen: () => false,
    commandPaletteOpen: () => false,
    replyBody: () => '',
    composeTo: () => '',
    composeCc: () => '',
    composeSubject: () => '',
    composeBody: () => '',
    composeShowCc: () => false,
    showComposeCc: () => undefined,
    discardCompose: () => undefined,
    contactSuggestions: () => [],
    contactSuggestField: () => null,
    contactSuggestHighlight: () => 0,
    pickContactSuggestion: () => undefined,
    moveContactHighlight: () => undefined,
    clearContactSuggestions: () => undefined,
    composeAttachments: () => [],
    replyAttachments: () => [],
    hasMoreMail: () => false,
    loadingMore: () => false,
    listFilling: () => false,
    loadMoreMail: async () => false,
    addComposeFiles: async () => undefined,
    removeComposeAttachment: () => undefined,
    addReplyFiles: async () => undefined,
    removeReplyAttachment: () => undefined,
    testNotification: async () => undefined,
    searchQuery: () => '',
    searchActive: () => false,
    searching: () => false,
    clearSearch: async () => undefined,
    fetchNewMailNow: () => undefined,
    onThreadListScrollNearBottom: () => undefined,
    mailView: () => 'inbox' as const,
    theme: () => ({
      mode: 'dark',
      accent: '#7c6af7',
      density: 'comfortable',
      blockRemoteImages: true,
      remoteImagesMode: 'ask' as const,
      replyDock: 'bottom' as const,
      fontFamily: 'sans' as const,
      fontSize: 'md' as const,
      uiLayout: 'list' as const,
    }),
    uiLayoutOptions: [],
    setUiLayout: () => undefined,
    isSplitLayout: () => false,
    showThreadList: () => true,
    showReadingPane: () => false,
    mailboxAskOpen: () => false,
    openMailboxAsk: () => undefined,
    closeMailboxAsk: () => undefined,
    toggleMailboxAsk: () => undefined,
    backToList: () => undefined,
    setFontFamily: () => undefined,
    setFontSize: () => undefined,
    recentOpens: () => [],
    suggestedReplies: () => [],
    applySuggestedReply: () => undefined,
    mailboxAskDraft: () => '',
    mailboxAskBusy: () => false,
    mailboxAskError: () => null,
    mailboxAskMessages: () => [],
    setMailboxAskDraft: () => undefined,
    sendMailboxAsk: async () => undefined,
    aiInsightOpen: () => false,
    aiInsightError: () => null,
    aiChatMessages: () => [],
    aiChatDraft: () => '',
    aiChatBusy: () => false,
    setAiChatDraft: () => undefined,
    sendAiChat: async () => undefined,
    lastAssistantReply: () => '',
    aiInsightText: () => '',
    aiInsightMode: () => null,
    closeAiInsight: () => undefined,
    insertInsightIntoReply: () => undefined,
    copyAiInsight: async () => undefined,
    setReplyDock: () => undefined,
    toggleReplyDock: () => undefined,
    settingsOpen: () => false,
    workflowsOpen: () => false,
    workflows: () => [],
    workflowRuns: () => [],
    workflowCatalog: () => null,
    workflowPath: () => null,
    workflowBusy: () => false,
    workflowDraft: () => null,
    workflowJobs: () => [],
    workflowActivityOpen: () => false,
    workflowReportOpen: () => false,
    workflowReport: () => null,
    openWorkflowReport: () => undefined,
    closeWorkflowReport: () => undefined,
    shellSection: () => 'mail' as const,
    showWorkflowsPage: () => false,
    openWorkflowActivity: () => undefined,
    closeWorkflowActivity: () => undefined,
    upsertWorkflowJob: () => undefined,
    openWorkflows: () => undefined,
    closeWorkflows: () => undefined,
    refreshWorkflows: async () => undefined,
    suggestWorkflow: async () => undefined,
    applyWorkflowDraft: () => undefined,
    saveWorkflowEdits: async () => undefined,
    approveWorkflow: async () => undefined,
    setWorkflowEnabled: async () => undefined,
    removeWorkflow: async () => undefined,
    runWorkflow: async () => undefined,
    stopWorkflowJob: async () => undefined,
    stopWorkflow: async () => undefined,
    liveWorkflowJob: () => undefined,
    helpOpen: () => false,
    searchFocusNonce: () => 0,
    accountMenuOpen: () => false,
    accentPresets: [],
    bootstrap: async () => undefined,
    selectThread: async () => undefined,
    selectNext: () => undefined,
    selectPrevious: () => undefined,
    openFocusedThread: () => undefined,
    listCursorId: () => null,
    focusedThreadId: () => null,
    isListCursor: () => false,
    openReply: () => undefined,
    openReplyAll: () => undefined,
    replyAll: () => false,
    replyToMessageId: () => null,
    closeReply: () => undefined,
    openCompose: () => undefined,
    closeCompose: () => undefined,
    setReplyBody: () => undefined,
    setComposeTo: () => undefined,
    setComposeSubject: () => undefined,
    setComposeBody: () => undefined,
    sendCompose: async () => undefined,
    sendReply: async () => undefined,
    archiveSelected: async () => undefined,
    undoArchive: async () => undefined,
    toggleStarSelected: async () => undefined,
    markUnreadSelected: async () => undefined,
    focusSearch: () => undefined,
    openHelp: () => undefined,
    closeHelp: () => undefined,
    toggleHelp: () => undefined,
    syncNow: async () => undefined,
    connectGmail: async () => undefined,
    toggleCommandPalette: () => undefined,
    closeCommandPalette: () => undefined,
    setSearchQuery: () => undefined,
    runSearch: async () => undefined,
    setMailView: async () => undefined,
    openLabel: async () => undefined,
    openCustomView: async () => undefined,
    refreshNavMeta: async () => undefined,
    addCustomViewFromSearch: async () => undefined,
    removeCustomView: async () => undefined,
    setBlockRemoteImages: () => undefined,
    setRemoteImagesMode: () => undefined,
    blockRemoteImagesNow: () => true,
    canUnlockRemoteImagesForThread: () => true,
    remoteImagesUnlockedThreadId: () => null,
    showRemoteImagesForThread: () => undefined,
    hideRemoteImagesForThread: () => undefined,
    runDailySummary: async () => undefined,
    aiSummarizeSelected: async () => undefined,
    aiDraftSelected: async () => undefined,
    openAttachment: () => undefined,
    closeImagePreview: () => undefined,
    closeAttachmentPreview: () => undefined,
    requestScrollReadingToTop: () => undefined,
    scrollReadingToTopNonce: () => 0,
    downloadAttachment: () => undefined,
    imagePreview: () => null,
    attachmentPreview: () => null,
    api: { attachmentUrl: () => '' },
    runPaletteCommand: () => undefined,
    toggleTheme: () => undefined,
    openSettings: () => undefined,
    closeSettings: () => undefined,
    toggleAccountMenu: () => undefined,
    closeAccountMenu: () => undefined,
    setThemeMode: () => undefined,
    setThemeAccent: () => undefined,
    setThemeDensity: () => undefined,
    addAccount: () => undefined,
    switchAccount: async () => undefined,
    removeActiveAccount: async () => undefined,
  };
}

describe('App', () => {
  beforeEach(async () => {
    await TestBed.configureTestingModule({
      imports: [App],
      providers: [
        provideHttpClient(),
        provideHttpClientTesting(),
        { provide: UiShellService, useValue: mockShell() },
      ],
    }).compileComponents();
  });

  it('should create the app', () => {
    const fixture = TestBed.createComponent(App);
    expect(fixture.componentInstance).toBeTruthy();
  });

  it('should render Local Mail shell', async () => {
    const fixture = TestBed.createComponent(App);
    await fixture.whenStable();
    const compiled = fixture.nativeElement as HTMLElement;
    expect(compiled.textContent).toContain('Local Mail');
    expect(compiled.textContent).toContain('Inbox');
  });
});
